### ISSUE TITLE
Introduce Metrics-tracking / Telemetry

### ISSUE THREAD

**Issue by yenicelik** [tensorlakeai/indexify#121]
We have logging to stdout through `tracing` which uses anysc tokio under the hood.
We want something similar that we can hook up to Prometheus or Grafana to show analyzed data. 
For this we can use https://github.com/open-telemetry/opentelemetry-rust

Amongst others, following items should be tracked (please edit this issue as more items come to mind): 
- [ ] cpu utilization
- [ ] api calls (per second)
- [ ] how many extractors are running
- [ ] how many executors are running
- [ ] how often the scheduler is invoked
- [x] Counters on API requests
- [x] Latency of api requests
- [x] Latency and counters of DB calls.
- [x] Latency and counters of extractor calls in the executor.

common system-level information: 
- https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/process-metrics/

**Comment by yenicelik** [comment]
@diptanu do you want every function to be instrumented? could use tracing::instrument decorators

**Comment by yenicelik** [comment]
Addressed partially by https://github.com/diptanu/indexify/pull/123 
metrics like disk usage, CPU usage, context switches are missing
